name: tugas_pbo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animator: ^3.0.0

  #* --- firebase ---
  # firebase_core_desktop: ^1.0.2
  # firebase_auth_desktop: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_app_check: ^0.1.4+2
  firebase_analytics: ^10.4.0
  firebase_messaging: ^14.6.0
  firebase_in_app_messaging: ^0.7.3
  firebase_database: ^10.2.0
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.0
  firebase_storage: ^11.2.0
  #*  --- firebase mock ---
  firebase_auth_mocks: ^0.11.0
  firebase_storage_mocks: ^0.6.1
  fake_cloud_firestore: ^2.4.1+1
  # google_sign_in_mocks: ^0.2.2
  #*  --- state management ---
  states_rebuilder: ^6.3.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  url_strategy: ^0.2.0
  #*  --- rest api ---
  http: ^0.13.6
  dio: ^5.1.2
  dio_log:
    git:
      url: https://github.com/flutterplugin/dio_log.git
      ref: dependabot/pub/dio-5.0.3
  # dio: ^4.0.4
  # dio_log: ^2.0.4

  #*  --- images ---
  flutter_fadein: ^2.0.0
  transparent_image: ^2.0.1
  shimmer: ^2.0.0
  image_picker: ^0.8.7+5
  flutter_cache_manager: ^3.3.0
  #*  --- tools ---
  device_preview: ^1.1.0
  validators: ^3.0.0
  overlay_support: ^2.1.0
  google_fonts: ^4.0.4
  intl: ^0.18.0
  connectivity_plus: ^4.0.0
  english_words: ^4.0.0
  uuid: ^3.0.7
  logger: ^1.3.0
  stack_trace: ^1.11.0
  keyboard_dismisser: ^3.0.0
  flutter_firebase_recaptcha: ^1.0.2
  flutter_native_splash: ^2.3.2
  multi_select_flutter: ^4.1.3
  sidebarx: ^0.16.2
  # collection: ^1.17.1
  # pinput: ^2.2.31
  # flutter_keyboard_visibility: ^5.4.1
  # pkg_master:
  #   path: ./packages/pkg_master
  # pkg_master:
  #   git:
  #     url: https://github.com/nostracode/pkg_master.git

# dependency_overrides:
#   firebase_core_platform_interface: 4.8.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/json/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader-Regular.ttf
        - asset: assets/fonts/Newsreader-Italic.ttf
          style: italic
        - asset: assets/fonts/Newsreader-Bold.ttf
          weight: 700
